### ISSUE TITLE
Prevent Telegram Bot to send too many messages

### ISSUE THREAD

**Issue by smartini87** [similicious/berlin-buergeramt-bot#5]
Could you tell what to implement in the code to not send too many messages via Telegram? Alloweded are only 20 messages per seconds.

As those appointments are fast taken I need to check the tool every second, but I do not need a Telegram message every second.

I tried to adjust the code in the index.js to the following but somehow it still sends too many messages.
My idea was to get the mod of the seconds of current time.

```
if (dates.length > 0) {
    const message = `Buergeramt appointments are available now! Check ${process.env.BOOKING_URL}`
    getTimeNow = new Date()
    if(getTimeNow % 3 == 2){
      await sendTelegramNotification(message)
    }
    else{
      console.log('Telegram messaging disabled. Wait 3 seconds...')
    }
  }
```

I also tried working with a boolean and a setTimeout function which sets the boolean variable back to true every 3 seonds, but also this does not work.
I fear it has something to do with the async logic? I am not a pro in Javascript.

Maybe the tool cna be adjusted with a new position in the .env file to set a timer for waiting before sending additional messages?

**Comment by similicious** [comment]
I don't think the solution with modulo is a reliable solution, because the code checking for an appointment takes probably longer than one second. However, it should reduce the amount of Requests to Telegram.

Thinking about it, I would advise against setting the interval to 1 second. Maybe every 30s, but not seconds. You wouldn't be able to react that fast anyway. Also you should avoid to be noticed by the admins of berlin.de.

You only get a message, when there is an appointment. So is there even a problem?
